<?php

$all_israel_cities = array(
  array('id' => '1','city' => 'אבו ג\'ווייעד )שבט('),
  array('id' => '2','city' => 'אבו גוש'),
  array('id' => '3','city' => 'אבו סנאן'),
  array('id' => '4','city' => 'אבו סריחאן )שבט('),
  array('id' => '5','city' => 'אבו עבדון )שבט('),
  array('id' => '6','city' => 'אבו עמאר )שבט('),
  array('id' => '7','city' => 'אבו עמרה )שבט('),
  array('id' => '8','city' => 'אבו קורינאת )שבט('),
  array('id' => '9','city' => 'אבו קרינאת )יישוב('),
  array('id' => '10','city' => 'אבו רובייעה )שבט('),
  array('id' => '11','city' => 'אבו רוקייק )שבט('),
  array('id' => '12','city' => 'אבו תלול'),
  array('id' => '13','city' => 'אבטין'),
  array('id' => '14','city' => 'אבטליון'),
  array('id' => '15','city' => 'אביאל'),
  array('id' => '16','city' => 'אביבים'),
  array('id' => '17','city' => 'אביגדור'),
  array('id' => '18','city' => 'אביחיל'),
  array('id' => '19','city' => 'אביטל'),
  array('id' => '20','city' => 'אביעזר'),
  array('id' => '21','city' => 'אבירים'),
  array('id' => '22','city' => 'אבן יהודה'),
  array('id' => '23','city' => 'אבן מנחם'),
  array('id' => '24','city' => 'אבן ספיר'),
  array('id' => '25','city' => 'אבן שמואל'),
  array('id' => '26','city' => 'אבני איתן'),
  array('id' => '27','city' => 'אבני חפץ'),
  array('id' => '28','city' => 'אבנת'),
  array('id' => '29','city' => 'אבשלום'),
  array('id' => '30','city' => 'אדורה'),
  array('id' => '31','city' => 'אדירים'),
  array('id' => '32','city' => 'אדמית'),
  array('id' => '33','city' => 'אדרת'),
  array('id' => '34','city' => 'אודים'),
  array('id' => '35','city' => 'אודם'),
  array('id' => '36','city' => 'אוהד'),
  array('id' => '37','city' => 'אום אל-פחם'),
  array('id' => '38','city' => 'אום אל-קוטוף'),
  array('id' => '39','city' => 'אום בטין'),
  array('id' => '40','city' => 'אומן'),
  array('id' => '41','city' => 'אומץ'),
  array('id' => '42','city' => 'אופקים'),
  array('id' => '43','city' => 'אור הגנוז'),
  array('id' => '44','city' => 'אור הנר'),
  array('id' => '45','city' => 'אור יהודה'),
  array('id' => '46','city' => 'אור עקיבא'),
  array('id' => '47','city' => 'אורה'),
  array('id' => '48','city' => 'אורות'),
  array('id' => '49','city' => 'אורטל'),
  array('id' => '50','city' => 'אורים'),
  array('id' => '51','city' => 'אורנים'),
  array('id' => '52','city' => 'אורנית'),
  array('id' => '53','city' => 'אושה'),
  array('id' => '54','city' => 'אזור'),
  array('id' => '55','city' => 'אחווה'),
  array('id' => '56','city' => 'אחוזם'),
  array('id' => '57','city' => 'אחוזת ברק'),
  array('id' => '58','city' => 'אחיהוד'),
  array('id' => '59','city' => 'אחיטוב'),
  array('id' => '60','city' => 'אחיסמך'),
  array('id' => '61','city' => 'אחיעזר'),
  array('id' => '62','city' => 'אטרש )שבט('),
  array('id' => '63','city' => 'איבים'),
  array('id' => '64','city' => 'אייל'),
  array('id' => '65','city' => 'איילת השחר'),
  array('id' => '66','city' => 'אילון'),
  array('id' => '67','city' => 'אילות'),
  array('id' => '68','city' => 'אילניה'),
  array('id' => '69','city' => 'אילת'),
  array('id' => '70','city' => 'אירוס'),
  array('id' => '71','city' => 'איתמר'),
  array('id' => '72','city' => 'איתן'),
  array('id' => '73','city' => 'איתנים'),
  array('id' => '74','city' => 'אכסאל'),
  array('id' => '75','city' => 'אל סייד'),
  array('id' => '76','city' => 'אלומה'),
  array('id' => '77','city' => 'אלומות'),
  array('id' => '78','city' => 'אלון הגליל'),
  array('id' => '79','city' => 'אלון מורה'),
  array('id' => '80','city' => 'אלון שבות'),
  array('id' => '81','city' => 'אלוני אבא'),
  array('id' => '82','city' => 'אלוני הבשן'),
  array('id' => '83','city' => 'אלוני יצחק'),
  array('id' => '84','city' => 'אלונים'),
  array('id' => '85','city' => 'אליאב'),
  array('id' => '86','city' => 'אליכין'),
  array('id' => '87','city' => 'אלי-עד'),
  array('id' => '88','city' => 'אליפז'),
  array('id' => '89','city' => 'אליפלט'),
  array('id' => '90','city' => 'אליקים'),
  array('id' => '91','city' => 'אלישיב'),
  array('id' => '92','city' => 'אלישמע'),
  array('id' => '93','city' => 'אלמגור'),
  array('id' => '94','city' => 'אלמוג'),
  array('id' => '95','city' => 'אלעד'),
  array('id' => '96','city' => 'אל-עזי'),
  array('id' => '97','city' => 'אלעזר'),
  array('id' => '98','city' => 'אל-עריאן'),
  array('id' => '99','city' => 'אלפי מנשה'),
  array('id' => '100','city' => 'אלקוש'),
  array('id' => '101','city' => 'אלקנה'),
  array('id' => '102','city' => 'אל-רום'),
  array('id' => '103','city' => 'אמונים'),
  array('id' => '104','city' => 'אמירים'),
  array('id' => '105','city' => 'אמנון'),
  array('id' => '106','city' => 'אמציה'),
  array('id' => '107','city' => 'אניעם'),
  array('id' => '108','city' => 'אסד )שבט('),
  array('id' => '109','city' => 'אספר'),
  array('id' => '110','city' => 'אעבלין'),
  array('id' => '111','city' => 'אעצם )שבט('),
  array('id' => '112','city' => 'אפיניש )שבט('),
  array('id' => '113','city' => 'אפיק'),
  array('id' => '114','city' => 'אפיקים'),
  array('id' => '115','city' => 'אפק'),
  array('id' => '116','city' => 'אפרת'),
  array('id' => '117','city' => 'ארבל'),
  array('id' => '118','city' => 'ארגמן'),
  array('id' => '119','city' => 'ארז'),
  array('id' => '120','city' => 'אריאל'),
  array('id' => '121','city' => 'ארסוף'),
  array('id' => '122','city' => 'אשבול'),
  array('id' => '123','city' => 'אשבל'),
  array('id' => '124','city' => 'אשדוד'),
  array('id' => '125','city' => 'אשדות יעקב  )איחוד('),
  array('id' => '126','city' => 'אשדות יעקב  )מאוחד('),
  array('id' => '127','city' => 'אשחר'),
  array('id' => '128','city' => 'אשכולות'),
  array('id' => '129','city' => 'אשל הנשיא'),
  array('id' => '130','city' => 'אשלים'),
  array('id' => '131','city' => 'אשקלון'),
  array('id' => '132','city' => 'אשרת'),
  array('id' => '133','city' => 'אשתאול'),
  array('id' => '134','city' => 'אתגר'),
  array('id' => '135','city' => 'באקה אל-גרביה'),
  array('id' => '136','city' => 'באר אורה'),
  array('id' => '137','city' => 'באר גנים'),
  array('id' => '138','city' => 'באר טוביה'),
  array('id' => '139','city' => 'באר יעקב'),
  array('id' => '140','city' => 'באר מילכה'),
  array('id' => '141','city' => 'באר שבע'),
  array('id' => '142','city' => 'בארות יצחק'),
  array('id' => '143','city' => 'בארותיים'),
  array('id' => '144','city' => 'בארי'),
  array('id' => '145','city' => 'בוסתן הגליל'),
  array('id' => '146','city' => 'בועיינה-נוג\'ידאת'),
  array('id' => '147','city' => 'בוקעאתא'),
  array('id' => '148','city' => 'בורגתה'),
  array('id' => '149','city' => 'בחן'),
  array('id' => '150','city' => 'בטחה'),
  array('id' => '151','city' => 'ביצרון'),
  array('id' => '152','city' => 'ביר אל-מכסור'),
  array('id' => '153','city' => 'ביר הדאג\''),
  array('id' => '154','city' => 'ביריה'),
  array('id' => '155','city' => 'בית אורן'),
  array('id' => '156','city' => 'בית אל'),
  array('id' => '157','city' => 'בית אלעזרי'),
  array('id' => '158','city' => 'בית אלפא'),
  array('id' => '159','city' => 'בית אריה'),
  array('id' => '160','city' => 'בית ברל'),
  array('id' => '161','city' => 'בית גוברין'),
  array('id' => '162','city' => 'בית גמליאל'),
  array('id' => '163','city' => 'בית ג\'ן'),
  array('id' => '164','city' => 'בית דגן'),
  array('id' => '165','city' => 'בית הגדי'),
  array('id' => '166','city' => 'בית הלוי'),
  array('id' => '167','city' => 'בית הלל'),
  array('id' => '168','city' => 'בית העמק'),
  array('id' => '169','city' => 'בית הערבה'),
  array('id' => '170','city' => 'בית השיטה'),
  array('id' => '171','city' => 'בית זיד'),
  array('id' => '172','city' => 'בית זית'),
  array('id' => '173','city' => 'בית זרע'),
  array('id' => '174','city' => 'בית חורון'),
  array('id' => '175','city' => 'בית חירות'),
  array('id' => '176','city' => 'בית חלקיה'),
  array('id' => '177','city' => 'בית חנן'),
  array('id' => '178','city' => 'בית חנניה'),
  array('id' => '179','city' => 'בית חשמונאי'),
  array('id' => '180','city' => 'בית יהושע'),
  array('id' => '181','city' => 'בית יוסף'),
  array('id' => '182','city' => 'בית ינאי'),
  array('id' => '183','city' => 'בית יצחק-שער חפר'),
  array('id' => '184','city' => 'בית לחם הגלילית'),
  array('id' => '185','city' => 'בית מאיר'),
  array('id' => '186','city' => 'בית נחמיה'),
  array('id' => '187','city' => 'בית ניר'),
  array('id' => '188','city' => 'בית נקופה'),
  array('id' => '189','city' => 'בית עובד'),
  array('id' => '190','city' => 'בית עוזיאל'),
  array('id' => '191','city' => 'בית עזרא'),
  array('id' => '192','city' => 'בית עריף'),
  array('id' => '193','city' => 'בית צבי'),
  array('id' => '194','city' => 'בית קמה'),
  array('id' => '195','city' => 'בית קשת'),
  array('id' => '196','city' => 'בית רבן'),
  array('id' => '197','city' => 'בית רימון'),
  array('id' => '198','city' => 'בית שאן'),
  array('id' => '199','city' => 'בית שמש'),
  array('id' => '200','city' => 'בית שערים'),
  array('id' => '201','city' => 'בית שקמה'),
  array('id' => '202','city' => 'ביתן אהרן'),
  array('id' => '203','city' => 'ביתר עילית'),
  array('id' => '204','city' => 'בלפוריה'),
  array('id' => '205','city' => 'בן זכאי'),
  array('id' => '206','city' => 'בן עמי'),
  array('id' => '207','city' => 'בן שמן )כפר נוער('),
  array('id' => '208','city' => 'בן שמן )מושב('),
  array('id' => '209','city' => 'בני ברק'),
  array('id' => '210','city' => 'בני דקלים'),
  array('id' => '211','city' => 'בני דרום'),
  array('id' => '212','city' => 'בני דרור'),
  array('id' => '213','city' => 'בני יהודה'),
  array('id' => '214','city' => 'בני נצרים'),
  array('id' => '215','city' => 'בני עטרות'),
  array('id' => '216','city' => 'בני עי"ש'),
  array('id' => '217','city' => 'בני ציון'),
  array('id' => '218','city' => 'בני ראם'),
  array('id' => '219','city' => 'בניה'),
  array('id' => '220','city' => 'בנימינה-גבעת עדה'),
  array('id' => '221','city' => 'בסמ"ה'),
  array('id' => '222','city' => 'בסמת טבעון'),
  array('id' => '223','city' => 'בענה'),
  array('id' => '224','city' => 'בצרה'),
  array('id' => '225','city' => 'בצת'),
  array('id' => '226','city' => 'בקוע'),
  array('id' => '227','city' => 'בקעות'),
  array('id' => '228','city' => 'בר גיורא'),
  array('id' => '229','city' => 'בר יוחאי'),
  array('id' => '230','city' => 'ברוכין'),
  array('id' => '231','city' => 'ברור חיל'),
  array('id' => '232','city' => 'ברוש'),
  array('id' => '233','city' => 'ברכה'),
  array('id' => '234','city' => 'ברכיה'),
  array('id' => '235','city' => 'ברעם'),
  array('id' => '236','city' => 'ברק'),
  array('id' => '237','city' => 'ברקאי'),
  array('id' => '238','city' => 'ברקן'),
  array('id' => '239','city' => 'ברקת'),
  array('id' => '240','city' => 'בת הדר'),
  array('id' => '241','city' => 'בת חן'),
  array('id' => '242','city' => 'בת חפר'),
  array('id' => '243','city' => 'בת חצור'),
  array('id' => '244','city' => 'בת ים'),
  array('id' => '245','city' => 'בת עין'),
  array('id' => '246','city' => 'בת שלמה'),
  array('id' => '247','city' => 'גאולי תימן'),
  array('id' => '248','city' => 'גאולים'),
  array('id' => '249','city' => 'גאליה'),
  array('id' => '250','city' => 'גבולות'),
  array('id' => '251','city' => 'גבים'),
  array('id' => '252','city' => 'גבע'),
  array('id' => '253','city' => 'גבע בנימין'),
  array('id' => '254','city' => 'גבע כרמל'),
  array('id' => '255','city' => 'גבעולים'),
  array('id' => '256','city' => 'גבעון החדשה'),
  array('id' => '257','city' => 'גבעות בר'),
  array('id' => '258','city' => 'גבעת אבני'),
  array('id' => '259','city' => 'גבעת אלה'),
  array('id' => '260','city' => 'גבעת ברנר'),
  array('id' => '261','city' => 'גבעת השלושה'),
  array('id' => '262','city' => 'גבעת זאב'),
  array('id' => '263','city' => 'גבעת חיים )איחוד('),
  array('id' => '264','city' => 'גבעת חיים )מאוחד('),
  array('id' => '265','city' => 'גבעת ח"ן'),
  array('id' => '266','city' => 'גבעת יואב'),
  array('id' => '267','city' => 'גבעת יערים'),
  array('id' => '268','city' => 'גבעת ישעיהו'),
  array('id' => '269','city' => 'גבעת כ"ח'),
  array('id' => '270','city' => 'גבעת ניל"י'),
  array('id' => '271','city' => 'גבעת עוז'),
  array('id' => '272','city' => 'גבעת שמואל'),
  array('id' => '273','city' => 'גבעת שמש'),
  array('id' => '274','city' => 'גבעת שפירא'),
  array('id' => '275','city' => 'גבעתי'),
  array('id' => '276','city' => 'גבעתיים'),
  array('id' => '277','city' => 'גברעם'),
  array('id' => '278','city' => 'גבת'),
  array('id' => '279','city' => 'גדות'),
  array('id' => '280','city' => 'ג\'דיידה-מכר'),
  array('id' => '281','city' => 'גדיש'),
  array('id' => '282','city' => 'גדעונה'),
  array('id' => '283','city' => 'גדרה'),
  array('id' => '284','city' => 'ג\'ולס'),
  array('id' => '285','city' => 'גונן'),
  array('id' => '286','city' => 'גורן'),
  array('id' => '287','city' => 'גורנות הגליל'),
  array('id' => '288','city' => 'גזית'),
  array('id' => '289','city' => 'גזר'),
  array('id' => '290','city' => 'גיאה'),
  array('id' => '291','city' => 'גיבתון'),
  array('id' => '292','city' => 'גיזו'),
  array('id' => '293','city' => 'גילון'),
  array('id' => '294','city' => 'גילת'),
  array('id' => '295','city' => 'גינוסר'),
  array('id' => '296','city' => 'גיניגר'),
  array('id' => '297','city' => 'גינתון'),
  array('id' => '298','city' => 'גיתה'),
  array('id' => '299','city' => 'גיתית'),
  array('id' => '300','city' => 'גלאון'),
  array('id' => '301','city' => 'ג\'לג\'וליה'),
  array('id' => '302','city' => 'גלגל'),
  array('id' => '303','city' => 'גליל ים'),
  array('id' => '304','city' => 'גלעד )אבן יצחק('),
  array('id' => '305','city' => 'גמזו'),
  array('id' => '306','city' => 'גן הדרום'),
  array('id' => '307','city' => 'גן השומרון'),
  array('id' => '308','city' => 'גן חיים'),
  array('id' => '309','city' => 'גן יאשיה'),
  array('id' => '310','city' => 'גן יבנה'),
  array('id' => '311','city' => 'גן נר'),
  array('id' => '312','city' => 'גן שורק'),
  array('id' => '313','city' => 'גן שלמה'),
  array('id' => '314','city' => 'גן שמואל'),
  array('id' => '315','city' => 'ג\'נאביב )שבט('),
  array('id' => '316','city' => 'גנות'),
  array('id' => '317','city' => 'גנות הדר'),
  array('id' => '318','city' => 'גני הדר'),
  array('id' => '319','city' => 'גני טל'),
  array('id' => '320','city' => 'גני יוחנן'),
  array('id' => '321','city' => 'גני מודיעין'),
  array('id' => '322','city' => 'גני עם'),
  array('id' => '323','city' => 'גני תקווה'),
  array('id' => '324','city' => 'ג\'סר א-זרקא'),
  array('id' => '325','city' => 'געש'),
  array('id' => '326','city' => 'געתון'),
  array('id' => '327','city' => 'גפן'),
  array('id' => '328','city' => 'גרופית'),
  array('id' => '329','city' => 'ג\'ש )גוש חלב('),
  array('id' => '330','city' => 'גשור'),
  array('id' => '331','city' => 'גשר'),
  array('id' => '332','city' => 'גשר הזיו'),
  array('id' => '333','city' => 'ג\'ת'),
  array('id' => '334','city' => 'גת )קיבוץ('),
  array('id' => '335','city' => 'גת רימון'),
  array('id' => '336','city' => 'דאלית אל-כרמל'),
  array('id' => '337','city' => 'דבורה'),
  array('id' => '338','city' => 'דבוריה'),
  array('id' => '339','city' => 'דבירה'),
  array('id' => '340','city' => 'דברת'),
  array('id' => '341','city' => 'דגניה א\''),
  array('id' => '342','city' => 'דגניה ב\''),
  array('id' => '343','city' => 'דוב"ב'),
  array('id' => '344','city' => 'דולב'),
  array('id' => '345','city' => 'דור'),
  array('id' => '346','city' => 'דורות'),
  array('id' => '347','city' => 'דחי'),
  array('id' => '348','city' => 'דייר אל-אסד'),
  array('id' => '349','city' => 'דייר חנא'),
  array('id' => '350','city' => 'דייר ראפאת'),
  array('id' => '351','city' => 'דימונה'),
  array('id' => '352','city' => 'דישון'),
  array('id' => '353','city' => 'דליה'),
  array('id' => '354','city' => 'דלתון'),
  array('id' => '355','city' => 'דמיידה'),
  array('id' => '356','city' => 'דן'),
  array('id' => '357','city' => 'דפנה'),
  array('id' => '358','city' => 'דקל'),
  array('id' => '359','city' => 'דריג\'את'),
  array('id' => '360','city' => 'האון'),
  array('id' => '361','city' => 'הבונים'),
  array('id' => '362','city' => 'הגושרים'),
  array('id' => '363','city' => 'הדר עם'),
  array('id' => '364','city' => 'הוד השרון'),
  array('id' => '365','city' => 'הודיה'),
  array('id' => '366','city' => 'הודיות'),
  array('id' => '367','city' => 'הוואשלה )שבט('),
  array('id' => '368','city' => 'הוזייל )שבט('),
  array('id' => '369','city' => 'הושעיה'),
  array('id' => '370','city' => 'הזורע'),
  array('id' => '371','city' => 'הזורעים'),
  array('id' => '372','city' => 'החותרים'),
  array('id' => '373','city' => 'היוגב'),
  array('id' => '374','city' => 'הילה'),
  array('id' => '375','city' => 'המעפיל'),
  array('id' => '376','city' => 'הסוללים'),
  array('id' => '377','city' => 'העוגן'),
  array('id' => '378','city' => 'הר אדר'),
  array('id' => '379','city' => 'הר גילה'),
  array('id' => '380','city' => 'הר עמשא'),
  array('id' => '381','city' => 'הראל'),
  array('id' => '382','city' => 'הרדוף'),
  array('id' => '383','city' => 'הרצליה'),
  array('id' => '384','city' => 'הררית'),
  array('id' => '385','city' => 'ורד יריחו'),
  array('id' => '386','city' => 'ורדון'),
  array('id' => '387','city' => 'זבארגה )שבט('),
  array('id' => '388','city' => 'זבדיאל'),
  array('id' => '389','city' => 'זוהר'),
  array('id' => '390','city' => 'זיקים'),
  array('id' => '391','city' => 'זיתן'),
  array('id' => '392','city' => 'זכרון יעקב'),
  array('id' => '393','city' => 'זכריה'),
  array('id' => '394','city' => 'זמר'),
  array('id' => '395','city' => 'זמרת'),
  array('id' => '396','city' => 'זנוח'),
  array('id' => '397','city' => 'זרועה'),
  array('id' => '398','city' => 'זרזיר'),
  array('id' => '399','city' => 'זרחיה'),
  array('id' => '400','city' => 'חבצלת השרון'),
  array('id' => '401','city' => 'חבר'),
  array('id' => '402','city' => 'חברון'),
  array('id' => '403','city' => 'חגור'),
  array('id' => '404','city' => 'חגי'),
  array('id' => '405','city' => 'חגלה'),
  array('id' => '406','city' => 'חדיד'),
  array('id' => '407','city' => 'חד-נס'),
  array('id' => '408','city' => 'חדרה'),
  array('id' => '409','city' => 'ח\'ואלד'),
  array('id' => '410','city' => 'ח\'ואלד )שבט('),
  array('id' => '411','city' => 'חוג\'ייראת )ד\'הרה('),
  array('id' => '412','city' => 'חולדה'),
  array('id' => '413','city' => 'חולון'),
  array('id' => '414','city' => 'חולית'),
  array('id' => '415','city' => 'חולתה'),
  array('id' => '416','city' => 'חוסן'),
  array('id' => '417','city' => 'חוסנייה'),
  array('id' => '418','city' => 'חופית'),
  array('id' => '419','city' => 'חוקוק'),
  array('id' => '420','city' => 'חורה'),
  array('id' => '421','city' => 'חורפיש'),
  array('id' => '422','city' => 'חורשים'),
  array('id' => '423','city' => 'חזון'),
  array('id' => '424','city' => 'חיבת ציון'),
  array('id' => '425','city' => 'חיננית'),
  array('id' => '426','city' => 'חיפה'),
  array('id' => '427','city' => 'חירות'),
  array('id' => '428','city' => 'חלוץ'),
  array('id' => '429','city' => 'חלמיש'),
  array('id' => '430','city' => 'חלץ'),
  array('id' => '431','city' => 'חמאם'),
  array('id' => '432','city' => 'חמד'),
  array('id' => '433','city' => 'חמדיה'),
  array('id' => '434','city' => 'חמדת'),
  array('id' => '435','city' => 'חמרה'),
  array('id' => '436','city' => 'חניאל'),
  array('id' => '437','city' => 'חניתה'),
  array('id' => '438','city' => 'חנתון'),
  array('id' => '439','city' => 'חספין'),
  array('id' => '440','city' => 'חפץ חיים'),
  array('id' => '441','city' => 'חפצי-בה'),
  array('id' => '442','city' => 'חצב'),
  array('id' => '443','city' => 'חצבה'),
  array('id' => '444','city' => 'חצור הגלילית'),
  array('id' => '445','city' => 'חצור-אשדוד'),
  array('id' => '446','city' => 'חצר בארותיים'),
  array('id' => '447','city' => 'חצרות חולדה'),
  array('id' => '448','city' => 'חצרות יסף'),
  array('id' => '449','city' => 'חצרות כ"ח'),
  array('id' => '450','city' => 'חצרים'),
  array('id' => '451','city' => 'חרב לאת'),
  array('id' => '452','city' => 'חרוצים'),
  array('id' => '453','city' => 'חריש'),
  array('id' => '454','city' => 'חרמש'),
  array('id' => '455','city' => 'חרשים'),
  array('id' => '456','city' => 'חשמונאים'),
  array('id' => '457','city' => 'טבריה'),
  array('id' => '458','city' => 'טובא-זנגריה'),
  array('id' => '459','city' => 'טורעאן'),
  array('id' => '460','city' => 'טייבה'),
  array('id' => '461','city' => 'טייבה )בעמק('),
  array('id' => '462','city' => 'טירה'),
  array('id' => '463','city' => 'טירת יהודה'),
  array('id' => '464','city' => 'טירת כרמל'),
  array('id' => '465','city' => 'טירת צבי'),
  array('id' => '466','city' => 'טל שחר'),
  array('id' => '467','city' => 'טל-אל'),
  array('id' => '468','city' => 'טללים'),
  array('id' => '469','city' => 'טלמון'),
  array('id' => '470','city' => 'טמרה'),
  array('id' => '471','city' => 'טמרה )יזרעאל('),
  array('id' => '472','city' => 'טנא'),
  array('id' => '473','city' => 'טפחות'),
  array('id' => '474','city' => 'יאנוח-ג\'ת'),
  array('id' => '475','city' => 'יבול'),
  array('id' => '476','city' => 'יבנאל'),
  array('id' => '477','city' => 'יבנה'),
  array('id' => '478','city' => 'יגור'),
  array('id' => '479','city' => 'יגל'),
  array('id' => '480','city' => 'יד בנימין'),
  array('id' => '481','city' => 'יד השמונה'),
  array('id' => '482','city' => 'יד חנה'),
  array('id' => '483','city' => 'יד מרדכי'),
  array('id' => '484','city' => 'יד נתן'),
  array('id' => '485','city' => 'יד רמב"ם'),
  array('id' => '486','city' => 'ידידה'),
  array('id' => '487','city' => 'יהוד-מונוסון'),
  array('id' => '488','city' => 'יהל'),
  array('id' => '489','city' => 'יובל'),
  array('id' => '490','city' => 'יובלים'),
  array('id' => '491','city' => 'יודפת'),
  array('id' => '492','city' => 'יונתן'),
  array('id' => '493','city' => 'יושיביה'),
  array('id' => '494','city' => 'יזרעאל'),
  array('id' => '495','city' => 'יחיעם'),
  array('id' => '496','city' => 'יטבתה'),
  array('id' => '497','city' => 'ייט"ב'),
  array('id' => '498','city' => 'יכיני'),
  array('id' => '499','city' => 'ינוב'),
  array('id' => '500','city' => 'ינון'),
  array('id' => '501','city' => 'יסוד המעלה'),
  array('id' => '502','city' => 'יסודות'),
  array('id' => '503','city' => 'יסעור'),
  array('id' => '504','city' => 'יעד'),
  array('id' => '505','city' => 'יעל'),
  array('id' => '506','city' => 'יעף'),
  array('id' => '507','city' => 'יערה'),
  array('id' => '508','city' => 'יפיע'),
  array('id' => '509','city' => 'יפית'),
  array('id' => '510','city' => 'יפעת'),
  array('id' => '511','city' => 'יפתח'),
  array('id' => '512','city' => 'יצהר'),
  array('id' => '513','city' => 'יציץ'),
  array('id' => '514','city' => 'יקום'),
  array('id' => '515','city' => 'יקיר'),
  array('id' => '516','city' => 'יקנעם )מושבה('),
  array('id' => '517','city' => 'יקנעם עילית'),
  array('id' => '518','city' => 'יראון'),
  array('id' => '519','city' => 'ירדנה'),
  array('id' => '520','city' => 'ירוחם'),
  array('id' => '521','city' => 'ירושלים'),
  array('id' => '522','city' => 'ירחיב'),
  array('id' => '523','city' => 'ירכא'),
  array('id' => '524','city' => 'ירקונה'),
  array('id' => '525','city' => 'ישע'),
  array('id' => '526','city' => 'ישעי'),
  array('id' => '527','city' => 'ישרש'),
  array('id' => '528','city' => 'יתד'),
  array('id' => '529','city' => 'יתיר'),
  array('id' => '530','city' => 'כאבול'),
  array('id' => '531','city' => 'כאוכב אבו אל-היג\'א'),
  array('id' => '532','city' => 'כברי'),
  array('id' => '533','city' => 'כדורי'),
  array('id' => '534','city' => 'כדיתה'),
  array('id' => '535','city' => 'כוכב השחר'),
  array('id' => '536','city' => 'כוכב יאיר'),
  array('id' => '537','city' => 'כוכב יעקב'),
  array('id' => '538','city' => 'כוכב מיכאל'),
  array('id' => '539','city' => 'כורזים'),
  array('id' => '540','city' => 'כחל'),
  array('id' => '541','city' => 'כחלה'),
  array('id' => '542','city' => 'כיסופים'),
  array('id' => '543','city' => 'כישור'),
  array('id' => '544','city' => 'כליל'),
  array('id' => '545','city' => 'כלנית'),
  array('id' => '546','city' => 'כמאנה'),
  array('id' => '547','city' => 'כמהין'),
  array('id' => '548','city' => 'כמון'),
  array('id' => '549','city' => 'כנות'),
  array('id' => '550','city' => 'כנף'),
  array('id' => '551','city' => 'כנרת )מושבה('),
  array('id' => '552','city' => 'כנרת )קבוצה('),
  array('id' => '553','city' => 'כסיפה'),
  array('id' => '554','city' => 'כסלון'),
  array('id' => '555','city' => 'כסרא-סמיע'),
  array('id' => '556','city' => 'כעביה-טבאש-חג\'אג\'רה'),
  array('id' => '557','city' => 'כפר אביב'),
  array('id' => '558','city' => 'כפר אדומים'),
  array('id' => '559','city' => 'כפר אוריה'),
  array('id' => '560','city' => 'כפר אחים'),
  array('id' => '561','city' => 'כפר ביאליק'),
  array('id' => '562','city' => 'כפר ביל"ו'),
  array('id' => '563','city' => 'כפר בלום'),
  array('id' => '564','city' => 'כפר בן נון'),
  array('id' => '565','city' => 'כפר ברא'),
  array('id' => '566','city' => 'כפר ברוך'),
  array('id' => '567','city' => 'כפר גדעון'),
  array('id' => '568','city' => 'כפר גלים'),
  array('id' => '569','city' => 'כפר גליקסון'),
  array('id' => '570','city' => 'כפר גלעדי'),
  array('id' => '571','city' => 'כפר דניאל'),
  array('id' => '572','city' => 'כפר האורנים'),
  array('id' => '573','city' => 'כפר החורש'),
  array('id' => '574','city' => 'כפר המכבי'),
  array('id' => '575','city' => 'כפר הנגיד'),
  array('id' => '576','city' => 'כפר הנוער הדתי'),
  array('id' => '577','city' => 'כפר הנשיא'),
  array('id' => '578','city' => 'כפר הס'),
  array('id' => '579','city' => 'כפר הרא"ה'),
  array('id' => '580','city' => 'כפר הרי"ף'),
  array('id' => '581','city' => 'כפר ויתקין'),
  array('id' => '582','city' => 'כפר ורבורג'),
  array('id' => '583','city' => 'כפר ורדים'),
  array('id' => '584','city' => 'כפר זוהרים'),
  array('id' => '585','city' => 'כפר זיתים'),
  array('id' => '586','city' => 'כפר חב"ד'),
  array('id' => '587','city' => 'כפר חושן'),
  array('id' => '588','city' => 'כפר חיטים'),
  array('id' => '589','city' => 'כפר חיים'),
  array('id' => '590','city' => 'כפר חנניה'),
  array('id' => '591','city' => 'כפר חסידים א\''),
  array('id' => '592','city' => 'כפר חסידים ב\''),
  array('id' => '593','city' => 'כפר חרוב'),
  array('id' => '594','city' => 'כפר טרומן'),
  array('id' => '595','city' => 'כפר יאסיף'),
  array('id' => '596','city' => 'כפר ידידיה'),
  array('id' => '597','city' => 'כפר יהושע'),
  array('id' => '598','city' => 'כפר יונה'),
  array('id' => '599','city' => 'כפר יחזקאל'),
  array('id' => '600','city' => 'כפר יעבץ'),
  array('id' => '601','city' => 'כפר כמא'),
  array('id' => '602','city' => 'כפר כנא'),
  array('id' => '603','city' => 'כפר מונש'),
  array('id' => '604','city' => 'כפר מימון'),
  array('id' => '605','city' => 'כפר מל"ל'),
  array('id' => '606','city' => 'כפר מנדא'),
  array('id' => '607','city' => 'כפר מנחם'),
  array('id' => '608','city' => 'כפר מסריק'),
  array('id' => '609','city' => 'כפר מצר'),
  array('id' => '610','city' => 'כפר מרדכי'),
  array('id' => '611','city' => 'כפר נטר'),
  array('id' => '612','city' => 'כפר סאלד'),
  array('id' => '613','city' => 'כפר סבא'),
  array('id' => '614','city' => 'כפר סילבר'),
  array('id' => '615','city' => 'כפר סירקין'),
  array('id' => '616','city' => 'כפר עבודה'),
  array('id' => '617','city' => 'כפר עזה'),
  array('id' => '618','city' => 'כפר עציון'),
  array('id' => '619','city' => 'כפר פינס'),
  array('id' => '620','city' => 'כפר קאסם'),
  array('id' => '621','city' => 'כפר קיש'),
  array('id' => '622','city' => 'כפר קרע'),
  array('id' => '623','city' => 'כפר ראש הנקרה'),
  array('id' => '624','city' => 'כפר רוזנואלד )זרעית('),
  array('id' => '625','city' => 'כפר רופין'),
  array('id' => '626','city' => 'כפר רות'),
  array('id' => '627','city' => 'כפר שמאי'),
  array('id' => '628','city' => 'כפר שמואל'),
  array('id' => '629','city' => 'כפר שמריהו'),
  array('id' => '630','city' => 'כפר תבור'),
  array('id' => '631','city' => 'כפר תפוח'),
  array('id' => '632','city' => 'כרי דשא'),
  array('id' => '633','city' => 'כרכום'),
  array('id' => '634','city' => 'כרם בן זמרה'),
  array('id' => '635','city' => 'כרם בן שמן'),
  array('id' => '636','city' => 'כרם יבנה )ישיבה('),
  array('id' => '637','city' => 'כרם מהר"ל'),
  array('id' => '638','city' => 'כרם שלום'),
  array('id' => '639','city' => 'כרמי יוסף'),
  array('id' => '640','city' => 'כרמי צור'),
  array('id' => '641','city' => 'כרמיאל'),
  array('id' => '642','city' => 'כרמיה'),
  array('id' => '643','city' => 'כרמים'),
  array('id' => '644','city' => 'כרמל'),
  array('id' => '645','city' => 'לא רשום'),
  array('id' => '646','city' => 'לבון'),
  array('id' => '647','city' => 'לביא'),
  array('id' => '648','city' => 'לבנים'),
  array('id' => '649','city' => 'להב'),
  array('id' => '650','city' => 'להבות הבשן'),
  array('id' => '651','city' => 'להבות חביבה'),
  array('id' => '652','city' => 'להבים'),
  array('id' => '653','city' => 'לוד'),
  array('id' => '654','city' => 'לוזית'),
  array('id' => '655','city' => 'לוחמי הגיטאות'),
  array('id' => '656','city' => 'לוטם'),
  array('id' => '657','city' => 'לוטן'),
  array('id' => '658','city' => 'לימן'),
  array('id' => '659','city' => 'לכיש'),
  array('id' => '660','city' => 'לפיד'),
  array('id' => '661','city' => 'לפידות'),
  array('id' => '662','city' => 'לקיה'),
  array('id' => '663','city' => 'מאור'),
  array('id' => '664','city' => 'מאיר שפיה'),
  array('id' => '665','city' => 'מבוא ביתר'),
  array('id' => '666','city' => 'מבוא דותן'),
  array('id' => '667','city' => 'מבוא חורון'),
  array('id' => '668','city' => 'מבוא חמה'),
  array('id' => '669','city' => 'מבוא מודיעים'),
  array('id' => '670','city' => 'מבואות ים'),
  array('id' => '671','city' => 'מבועים'),
  array('id' => '672','city' => 'מבטחים'),
  array('id' => '673','city' => 'מבקיעים'),
  array('id' => '674','city' => 'מבשרת ציון'),
  array('id' => '675','city' => 'מגאר'),
  array('id' => '676','city' => 'מג\'ד אל-כרום'),
  array('id' => '677','city' => 'מגדים'),
  array('id' => '678','city' => 'מגדל'),
  array('id' => '679','city' => 'מגדל העמק'),
  array('id' => '680','city' => 'מגדל עוז'),
  array('id' => '681','city' => 'מג\'דל שמס'),
  array('id' => '682','city' => 'מגדלים'),
  array('id' => '683','city' => 'מגידו'),
  array('id' => '684','city' => 'מגל'),
  array('id' => '685','city' => 'מגן'),
  array('id' => '686','city' => 'מגן שאול'),
  array('id' => '687','city' => 'מגשימים'),
  array('id' => '688','city' => 'מדרך עוז'),
  array('id' => '689','city' => 'מדרשת בן גוריון'),
  array('id' => '690','city' => 'מדרשת רופין'),
  array('id' => '691','city' => 'מודיעין עילית'),
  array('id' => '692','city' => 'מודיעין-מכבים-רעות'),
  array('id' => '693','city' => 'מולדה'),
  array('id' => '694','city' => 'מולדת'),
  array('id' => '695','city' => 'מוצא עילית'),
  array('id' => '696','city' => 'מוקייבלה'),
  array('id' => '697','city' => 'מורן'),
  array('id' => '698','city' => 'מורשת'),
  array('id' => '699','city' => 'מזור'),
  array('id' => '700','city' => 'מזכרת בתיה'),
  array('id' => '701','city' => 'מזרע'),
  array('id' => '702','city' => 'מזרעה'),
  array('id' => '703','city' => 'מחולה'),
  array('id' => '704','city' => 'מחנה הילה'),
  array('id' => '705','city' => 'מחנה טלי'),
  array('id' => '706','city' => 'מחנה יהודית'),
  array('id' => '707','city' => 'מחנה יוכבד'),
  array('id' => '708','city' => 'מחנה יפה'),
  array('id' => '709','city' => 'מחנה יתיר'),
  array('id' => '710','city' => 'מחנה מרים'),
  array('id' => '711','city' => 'מחנה עדי'),
  array('id' => '712','city' => 'מחנה תל נוף'),
  array('id' => '713','city' => 'מחניים'),
  array('id' => '714','city' => 'מחסיה'),
  array('id' => '715','city' => 'מטולה'),
  array('id' => '716','city' => 'מטע'),
  array('id' => '717','city' => 'מי עמי'),
  array('id' => '718','city' => 'מיטב'),
  array('id' => '719','city' => 'מייסר'),
  array('id' => '720','city' => 'מיצר'),
  array('id' => '721','city' => 'מירב'),
  array('id' => '722','city' => 'מירון'),
  array('id' => '723','city' => 'מישר'),
  array('id' => '724','city' => 'מיתר'),
  array('id' => '725','city' => 'מכורה'),
  array('id' => '726','city' => 'מכחול'),
  array('id' => '727','city' => 'מכמורת'),
  array('id' => '728','city' => 'מכמנים'),
  array('id' => '729','city' => 'מלאה'),
  array('id' => '730','city' => 'מלילות'),
  array('id' => '731','city' => 'מלכיה'),
  array('id' => '732','city' => 'מלכישוע'),
  array('id' => '733','city' => 'מנוחה'),
  array('id' => '734','city' => 'מנוף'),
  array('id' => '735','city' => 'מנות'),
  array('id' => '736','city' => 'מנחמיה'),
  array('id' => '737','city' => 'מנרה'),
  array('id' => '738','city' => 'מנשית זבדה'),
  array('id' => '739','city' => 'מסד'),
  array('id' => '740','city' => 'מסדה'),
  array('id' => '741','city' => 'מסילות'),
  array('id' => '742','city' => 'מסילת ציון'),
  array('id' => '743','city' => 'מסלול'),
  array('id' => '744','city' => 'מסעדה'),
  array('id' => '745','city' => 'מסעודין אל-עזאזמה'),
  array('id' => '746','city' => 'מעברות'),
  array('id' => '747','city' => 'מעגלים'),
  array('id' => '748','city' => 'מעגן'),
  array('id' => '749','city' => 'מעגן מיכאל'),
  array('id' => '750','city' => 'מעוז חיים'),
  array('id' => '751','city' => 'מעון'),
  array('id' => '752','city' => 'מעונה'),
  array('id' => '753','city' => 'מעיליא'),
  array('id' => '754','city' => 'מעין ברוך'),
  array('id' => '755','city' => 'מעין צבי'),
  array('id' => '756','city' => 'מעלה אדומים'),
  array('id' => '757','city' => 'מעלה אפרים'),
  array('id' => '758','city' => 'מעלה גלבוע'),
  array('id' => '759','city' => 'מעלה גמלא'),
  array('id' => '760','city' => 'מעלה החמישה'),
  array('id' => '761','city' => 'מעלה לבונה'),
  array('id' => '762','city' => 'מעלה מכמש'),
  array('id' => '763','city' => 'מעלה עירון'),
  array('id' => '764','city' => 'מעלה עמוס'),
  array('id' => '765','city' => 'מעלה שומרון'),
  array('id' => '766','city' => 'מעלות-תרשיחא'),
  array('id' => '767','city' => 'מענית'),
  array('id' => '768','city' => 'מעש'),
  array('id' => '769','city' => 'מפלסים'),
  array('id' => '770','city' => 'מצדות יהודה'),
  array('id' => '771','city' => 'מצובה'),
  array('id' => '772','city' => 'מצליח'),
  array('id' => '773','city' => 'מצפה'),
  array('id' => '774','city' => 'מצפה אבי"ב'),
  array('id' => '775','city' => 'מצפה אילן'),
  array('id' => '776','city' => 'מצפה יריחו'),
  array('id' => '777','city' => 'מצפה נטופה'),
  array('id' => '778','city' => 'מצפה רמון'),
  array('id' => '779','city' => 'מצפה שלם'),
  array('id' => '780','city' => 'מצר'),
  array('id' => '781','city' => 'מקווה ישראל'),
  array('id' => '782','city' => 'מרגליות'),
  array('id' => '783','city' => 'מרום גולן'),
  array('id' => '784','city' => 'מרחב עם'),
  array('id' => '785','city' => 'מרחביה )מושב('),
  array('id' => '786','city' => 'מרחביה )קיבוץ('),
  array('id' => '787','city' => 'מרכז שפירא'),
  array('id' => '788','city' => 'משאבי שדה'),
  array('id' => '789','city' => 'משגב דב'),
  array('id' => '790','city' => 'משגב עם'),
  array('id' => '791','city' => 'משהד'),
  array('id' => '792','city' => 'משואה'),
  array('id' => '793','city' => 'משואות יצחק'),
  array('id' => '794','city' => 'משכיות'),
  array('id' => '795','city' => 'משמר איילון'),
  array('id' => '796','city' => 'משמר דוד'),
  array('id' => '797','city' => 'משמר הירדן'),
  array('id' => '798','city' => 'משמר הנגב'),
  array('id' => '799','city' => 'משמר העמק'),
  array('id' => '800','city' => 'משמר השבעה'),
  array('id' => '801','city' => 'משמר השרון'),
  array('id' => '802','city' => 'משמרות'),
  array('id' => '803','city' => 'משמרת'),
  array('id' => '804','city' => 'משען'),
  array('id' => '805','city' => 'מתן'),
  array('id' => '806','city' => 'מתת'),
  array('id' => '807','city' => 'מתתיהו'),
  array('id' => '808','city' => 'נאות גולן'),
  array('id' => '809','city' => 'נאות הכיכר'),
  array('id' => '810','city' => 'נאות מרדכי'),
  array('id' => '811','city' => 'נאות סמדר'),
  array('id' => '812','city' => 'נאעורה'),
  array('id' => '813','city' => 'נבטים'),
  array('id' => '814','city' => 'נגבה'),
  array('id' => '815','city' => 'נגוהות'),
  array('id' => '816','city' => 'נהורה'),
  array('id' => '817','city' => 'נהלל'),
  array('id' => '818','city' => 'נהריה'),
  array('id' => '819','city' => 'נוב'),
  array('id' => '820','city' => 'נוגה'),
  array('id' => '821','city' => 'נווה'),
  array('id' => '822','city' => 'נווה אבות'),
  array('id' => '823','city' => 'נווה אור'),
  array('id' => '824','city' => 'נווה אטי"ב'),
  array('id' => '825','city' => 'נווה אילן'),
  array('id' => '826','city' => 'נווה איתן'),
  array('id' => '827','city' => 'נווה דניאל'),
  array('id' => '828','city' => 'נווה זוהר'),
  array('id' => '829','city' => 'נווה זיו'),
  array('id' => '830','city' => 'נווה חריף'),
  array('id' => '831','city' => 'נווה ים'),
  array('id' => '832','city' => 'נווה ימין'),
  array('id' => '833','city' => 'נווה ירק'),
  array('id' => '834','city' => 'נווה מבטח'),
  array('id' => '835','city' => 'נווה מיכאל'),
  array('id' => '836','city' => 'נווה שלום'),
  array('id' => '837','city' => 'נועם'),
  array('id' => '838','city' => 'נוף איילון'),
  array('id' => '839','city' => 'נופים'),
  array('id' => '840','city' => 'נופית'),
  array('id' => '841','city' => 'נופך'),
  array('id' => '842','city' => 'נוקדים'),
  array('id' => '843','city' => 'נורדיה'),
  array('id' => '844','city' => 'נורית'),
  array('id' => '845','city' => 'נחושה'),
  array('id' => '846','city' => 'נחל עוז'),
  array('id' => '847','city' => 'נחלה'),
  array('id' => '848','city' => 'נחליאל'),
  array('id' => '849','city' => 'נחלים'),
  array('id' => '850','city' => 'נחם'),
  array('id' => '851','city' => 'נחף'),
  array('id' => '852','city' => 'נחשולים'),
  array('id' => '853','city' => 'נחשון'),
  array('id' => '854','city' => 'נחשונים'),
  array('id' => '855','city' => 'נטועה'),
  array('id' => '856','city' => 'נטור'),
  array('id' => '857','city' => 'נטע'),
  array('id' => '858','city' => 'נטעים'),
  array('id' => '859','city' => 'נטף'),
  array('id' => '860','city' => 'ניין'),
  array('id' => '861','city' => 'ניל"י'),
  array('id' => '862','city' => 'ניצן'),
  array('id' => '863','city' => 'ניצן ב\''),
  array('id' => '864','city' => 'ניצנה )קהילת חינוך('),
  array('id' => '865','city' => 'ניצני סיני'),
  array('id' => '866','city' => 'ניצני עוז'),
  array('id' => '867','city' => 'ניצנים'),
  array('id' => '868','city' => 'ניר אליהו'),
  array('id' => '869','city' => 'ניר בנים'),
  array('id' => '870','city' => 'ניר גלים'),
  array('id' => '871','city' => 'ניר דוד )תל עמל('),
  array('id' => '872','city' => 'ניר ח"ן'),
  array('id' => '873','city' => 'ניר יפה'),
  array('id' => '874','city' => 'ניר יצחק'),
  array('id' => '875','city' => 'ניר ישראל'),
  array('id' => '876','city' => 'ניר משה'),
  array('id' => '877','city' => 'ניר עוז'),
  array('id' => '878','city' => 'ניר עם'),
  array('id' => '879','city' => 'ניר עציון'),
  array('id' => '880','city' => 'ניר עקיבא'),
  array('id' => '881','city' => 'ניר צבי'),
  array('id' => '882','city' => 'נירים'),
  array('id' => '883','city' => 'נירית'),
  array('id' => '884','city' => 'נירן'),
  array('id' => '885','city' => 'נס הרים'),
  array('id' => '886','city' => 'נס עמים'),
  array('id' => '887','city' => 'נס ציונה'),
  array('id' => '888','city' => 'נעורים'),
  array('id' => '889','city' => 'נעלה'),
  array('id' => '890','city' => 'נעמ"ה'),
  array('id' => '891','city' => 'נען'),
  array('id' => '892','city' => 'נצאצרה )שבט('),
  array('id' => '893','city' => 'נצר חזני'),
  array('id' => '894','city' => 'נצר סרני'),
  array('id' => '895','city' => 'נצרת'),
  array('id' => '896','city' => 'נצרת עילית'),
  array('id' => '897','city' => 'נשר'),
  array('id' => '898','city' => 'נתיב הגדוד'),
  array('id' => '899','city' => 'נתיב הל"ה'),
  array('id' => '900','city' => 'נתיב העשרה'),
  array('id' => '901','city' => 'נתיב השיירה'),
  array('id' => '902','city' => 'נתיבות'),
  array('id' => '903','city' => 'נתניה'),
  array('id' => '904','city' => 'סאג\'ור'),
  array('id' => '905','city' => 'סאסא'),
  array('id' => '906','city' => 'סביון'),
  array('id' => '907','city' => 'סגולה'),
  array('id' => '908','city' => 'סואעד )חמרייה('),
  array('id' => '909','city' => 'סואעד )כמאנה( )שבט('),
  array('id' => '910','city' => 'סולם'),
  array('id' => '911','city' => 'סוסיה'),
  array('id' => '912','city' => 'סופה'),
  array('id' => '913','city' => 'סח\'נין'),
  array('id' => '914','city' => 'סייד )שבט('),
  array('id' => '915','city' => 'סלמה'),
  array('id' => '916','city' => 'סלעית'),
  array('id' => '917','city' => 'סמר'),
  array('id' => '918','city' => 'סנסנה'),
  array('id' => '919','city' => 'סעד'),
  array('id' => '920','city' => 'סער'),
  array('id' => '921','city' => 'ספיר'),
  array('id' => '922','city' => 'סתריה'),
  array('id' => '923','city' => 'עבדון'),
  array('id' => '924','city' => 'עברון'),
  array('id' => '925','city' => 'עגור'),
  array('id' => '926','city' => 'ע\'ג\'ר'),
  array('id' => '927','city' => 'עדי'),
  array('id' => '928','city' => 'עדנים'),
  array('id' => '929','city' => 'עוזה'),
  array('id' => '930','city' => 'עוזייר'),
  array('id' => '931','city' => 'עולש'),
  array('id' => '932','city' => 'עומר'),
  array('id' => '933','city' => 'עופר'),
  array('id' => '934','city' => 'עופרה'),
  array('id' => '935','city' => 'עוצם'),
  array('id' => '936','city' => 'עוקבי )בנו עוקבה('),
  array('id' => '937','city' => 'עזוז'),
  array('id' => '938','city' => 'עזר'),
  array('id' => '939','city' => 'עזריאל'),
  array('id' => '940','city' => 'עזריה'),
  array('id' => '941','city' => 'עזריקם'),
  array('id' => '942','city' => 'עטאוונה )שבט('),
  array('id' => '943','city' => 'עטרת'),
  array('id' => '944','city' => 'עידן'),
  array('id' => '945','city' => 'עיילבון'),
  array('id' => '946','city' => 'עיינות'),
  array('id' => '947','city' => 'עילוט'),
  array('id' => '948','city' => 'עין איילה'),
  array('id' => '949','city' => 'עין אל-אסד'),
  array('id' => '950','city' => 'עין גב'),
  array('id' => '951','city' => 'עין גדי'),
  array('id' => '952','city' => 'עין דור'),
  array('id' => '953','city' => 'עין הבשור'),
  array('id' => '954','city' => 'עין הוד'),
  array('id' => '955','city' => 'עין החורש'),
  array('id' => '956','city' => 'עין המפרץ'),
  array('id' => '957','city' => 'עין הנצי"ב'),
  array('id' => '958','city' => 'עין העמק'),
  array('id' => '959','city' => 'עין השופט'),
  array('id' => '960','city' => 'עין השלושה'),
  array('id' => '961','city' => 'עין ורד'),
  array('id' => '962','city' => 'עין זיוון'),
  array('id' => '963','city' => 'עין חוד'),
  array('id' => '964','city' => 'עין חצבה'),
  array('id' => '965','city' => 'עין חרוד )איחוד('),
  array('id' => '966','city' => 'עין חרוד )מאוחד('),
  array('id' => '967','city' => 'עין יהב'),
  array('id' => '968','city' => 'עין יעקב'),
  array('id' => '969','city' => 'עין כרם-בי"ס חקלאי'),
  array('id' => '970','city' => 'עין כרמל'),
  array('id' => '971','city' => 'עין מאהל'),
  array('id' => '972','city' => 'עין נקובא'),
  array('id' => '973','city' => 'עין עירון'),
  array('id' => '974','city' => 'עין צורים'),
  array('id' => '975','city' => 'עין קנייא'),
  array('id' => '976','city' => 'עין ראפה'),
  array('id' => '977','city' => 'עין שמר'),
  array('id' => '978','city' => 'עין שריד'),
  array('id' => '979','city' => 'עין תמר'),
  array('id' => '980','city' => 'עינת'),
  array('id' => '981','city' => 'עיר אובות'),
  array('id' => '982','city' => 'עכו'),
  array('id' => '983','city' => 'עלומים'),
  array('id' => '984','city' => 'עלי'),
  array('id' => '985','city' => 'עלי זהב'),
  array('id' => '986','city' => 'עלמה'),
  array('id' => '987','city' => 'עלמון'),
  array('id' => '988','city' => 'עמוקה'),
  array('id' => '989','city' => 'עמינדב'),
  array('id' => '990','city' => 'עמיעד'),
  array('id' => '991','city' => 'עמיעוז'),
  array('id' => '992','city' => 'עמיקם'),
  array('id' => '993','city' => 'עמיר'),
  array('id' => '994','city' => 'עמנואל'),
  array('id' => '995','city' => 'עמקה'),
  array('id' => '996','city' => 'ענב'),
  array('id' => '997','city' => 'עספיא'),
  array('id' => '998','city' => 'עפולה'),
  array('id' => '999','city' => 'עץ אפרים'),
  array('id' => '1000','city' => 'עצמון שגב'),
  array('id' => '1001','city' => 'עראבה'),
  array('id' => '1002','city' => 'עראמשה'),
  array('id' => '1003','city' => 'ערב אל נעים'),
  array('id' => '1004','city' => 'ערד'),
  array('id' => '1005','city' => 'ערוגות'),
  array('id' => '1006','city' => 'ערערה'),
  array('id' => '1007','city' => 'ערערה-בנגב'),
  array('id' => '1008','city' => 'עשרת'),
  array('id' => '1009','city' => 'עתלית'),
  array('id' => '1010','city' => 'עתניאל'),
  array('id' => '1011','city' => 'פארן'),
  array('id' => '1012','city' => 'פדואל'),
  array('id' => '1013','city' => 'פדויים'),
  array('id' => '1014','city' => 'פדיה'),
  array('id' => '1015','city' => 'פוריה - כפר עבודה'),
  array('id' => '1016','city' => 'פוריה - נווה עובד'),
  array('id' => '1017','city' => 'פוריה עילית'),
  array('id' => '1018','city' => 'פוריידיס'),
  array('id' => '1019','city' => 'פורת'),
  array('id' => '1020','city' => 'פטיש'),
  array('id' => '1021','city' => 'פלך'),
  array('id' => '1022','city' => 'פלמחים'),
  array('id' => '1023','city' => 'פני חבר'),
  array('id' => '1024','city' => 'פסגות'),
  array('id' => '1025','city' => 'פסוטה'),
  array('id' => '1026','city' => 'פעמי תש"ז'),
  array('id' => '1027','city' => 'פצאל'),
  array('id' => '1028','city' => 'פקיעין )בוקייעה('),
  array('id' => '1029','city' => 'פקיעין חדשה'),
  array('id' => '1030','city' => 'פרדס חנה-כרכור'),
  array('id' => '1031','city' => 'פרדסיה'),
  array('id' => '1032','city' => 'פרוד'),
  array('id' => '1033','city' => 'פרזון'),
  array('id' => '1034','city' => 'פרי גן'),
  array('id' => '1035','city' => 'פתח תקווה'),
  array('id' => '1036','city' => 'פתחיה'),
  array('id' => '1037','city' => 'צאלים'),
  array('id' => '1038','city' => 'צביה'),
  array('id' => '1039','city' => 'צבעון'),
  array('id' => '1040','city' => 'צובה'),
  array('id' => '1041','city' => 'צוחר'),
  array('id' => '1042','city' => 'צופיה'),
  array('id' => '1043','city' => 'צופים'),
  array('id' => '1044','city' => 'צופית'),
  array('id' => '1045','city' => 'צופר'),
  array('id' => '1046','city' => 'צוקי ים'),
  array('id' => '1047','city' => 'צוקים'),
  array('id' => '1048','city' => 'צור הדסה'),
  array('id' => '1049','city' => 'צור יצחק'),
  array('id' => '1050','city' => 'צור משה'),
  array('id' => '1051','city' => 'צור נתן'),
  array('id' => '1052','city' => 'צוריאל'),
  array('id' => '1053','city' => 'צורית'),
  array('id' => '1054','city' => 'ציפורי'),
  array('id' => '1055','city' => 'צלפון'),
  array('id' => '1056','city' => 'צנדלה'),
  array('id' => '1057','city' => 'צפריה'),
  array('id' => '1058','city' => 'צפרירים'),
  array('id' => '1059','city' => 'צפת'),
  array('id' => '1060','city' => 'צרופה'),
  array('id' => '1061','city' => 'צרעה'),
  array('id' => '1062','city' => 'קבועה )שבט('),
  array('id' => '1063','city' => 'קבוצת יבנה'),
  array('id' => '1064','city' => 'קדומים'),
  array('id' => '1065','city' => 'קדימה-צורן'),
  array('id' => '1066','city' => 'קדמה'),
  array('id' => '1067','city' => 'קדמת צבי'),
  array('id' => '1068','city' => 'קדר'),
  array('id' => '1069','city' => 'קדרון'),
  array('id' => '1070','city' => 'קדרים'),
  array('id' => '1071','city' => 'קודייראת א-צאנע)שבט('),
  array('id' => '1072','city' => 'קוואעין )שבט('),
  array('id' => '1073','city' => 'קוממיות'),
  array('id' => '1074','city' => 'קורנית'),
  array('id' => '1075','city' => 'קטורה'),
  array('id' => '1076','city' => 'קיסריה'),
  array('id' => '1077','city' => 'קלחים'),
  array('id' => '1078','city' => 'קליה'),
  array('id' => '1079','city' => 'קלנסווה'),
  array('id' => '1080','city' => 'קלע'),
  array('id' => '1081','city' => 'קציר'),
  array('id' => '1082','city' => 'קצר א-סר'),
  array('id' => '1083','city' => 'קצרין'),
  array('id' => '1084','city' => 'קרית אונו'),
  array('id' => '1085','city' => 'קרית ארבע'),
  array('id' => '1086','city' => 'קרית אתא'),
  array('id' => '1087','city' => 'קרית ביאליק'),
  array('id' => '1088','city' => 'קרית גת'),
  array('id' => '1089','city' => 'קרית טבעון'),
  array('id' => '1090','city' => 'קרית ים'),
  array('id' => '1091','city' => 'קרית יערים'),
  array('id' => '1092','city' => 'קרית יערים)מוסד('),
  array('id' => '1093','city' => 'קרית מוצקין'),
  array('id' => '1094','city' => 'קרית מלאכי'),
  array('id' => '1095','city' => 'קרית נטפים'),
  array('id' => '1096','city' => 'קרית ענבים'),
  array('id' => '1097','city' => 'קרית עקרון'),
  array('id' => '1098','city' => 'קרית שלמה'),
  array('id' => '1099','city' => 'קרית שמונה'),
  array('id' => '1100','city' => 'קרני שומרון'),
  array('id' => '1101','city' => 'קשת'),
  array('id' => '1102','city' => 'ראמה'),
  array('id' => '1103','city' => 'ראס אל-עין'),
  array('id' => '1104','city' => 'ראס עלי'),
  array('id' => '1105','city' => 'ראש העין'),
  array('id' => '1106','city' => 'ראש פינה'),
  array('id' => '1107','city' => 'ראש צורים'),
  array('id' => '1108','city' => 'ראשון לציון'),
  array('id' => '1109','city' => 'רבבה'),
  array('id' => '1110','city' => 'רבדים'),
  array('id' => '1111','city' => 'רביבים'),
  array('id' => '1112','city' => 'רביד'),
  array('id' => '1113','city' => 'רגבה'),
  array('id' => '1114','city' => 'רגבים'),
  array('id' => '1115','city' => 'רהט'),
  array('id' => '1116','city' => 'רווחה'),
  array('id' => '1117','city' => 'רוויה'),
  array('id' => '1118','city' => 'רוח מדבר'),
  array('id' => '1119','city' => 'רוחמה'),
  array('id' => '1120','city' => 'רומאנה'),
  array('id' => '1121','city' => 'רומת הייב'),
  array('id' => '1122','city' => 'רועי'),
  array('id' => '1123','city' => 'רותם'),
  array('id' => '1124','city' => 'רחוב'),
  array('id' => '1125','city' => 'רחובות'),
  array('id' => '1126','city' => 'רחלים'),
  array('id' => '1127','city' => 'ריחאניה'),
  array('id' => '1128','city' => 'ריחן'),
  array('id' => '1129','city' => 'ריינה'),
  array('id' => '1130','city' => 'רימונים'),
  array('id' => '1131','city' => 'רינתיה'),
  array('id' => '1132','city' => 'רכסים'),
  array('id' => '1133','city' => 'רם-און'),
  array('id' => '1134','city' => 'רמות'),
  array('id' => '1135','city' => 'רמות השבים'),
  array('id' => '1136','city' => 'רמות מאיר'),
  array('id' => '1137','city' => 'רמות מנשה'),
  array('id' => '1138','city' => 'רמות נפתלי'),
  array('id' => '1139','city' => 'רמלה'),
  array('id' => '1140','city' => 'רמת גן'),
  array('id' => '1141','city' => 'רמת דוד'),
  array('id' => '1142','city' => 'רמת הכובש'),
  array('id' => '1143','city' => 'רמת השופט'),
  array('id' => '1144','city' => 'רמת השרון'),
  array('id' => '1145','city' => 'רמת יוחנן'),
  array('id' => '1146','city' => 'רמת ישי'),
  array('id' => '1147','city' => 'רמת מגשימים'),
  array('id' => '1148','city' => 'רמת צבי'),
  array('id' => '1149','city' => 'רמת רזיאל'),
  array('id' => '1150','city' => 'רמת רחל'),
  array('id' => '1151','city' => 'רנן'),
  array('id' => '1152','city' => 'רעים'),
  array('id' => '1153','city' => 'רעננה'),
  array('id' => '1154','city' => 'רקפת'),
  array('id' => '1155','city' => 'רשפון'),
  array('id' => '1156','city' => 'רשפים'),
  array('id' => '1157','city' => 'רתמים'),
  array('id' => '1158','city' => 'שאר ישוב'),
  array('id' => '1159','city' => 'שבי ציון'),
  array('id' => '1160','city' => 'שבי שומרון'),
  array('id' => '1161','city' => 'שבלי - אום אל-גנם'),
  array('id' => '1162','city' => 'שגב-שלום'),
  array('id' => '1163','city' => 'שדה אילן'),
  array('id' => '1164','city' => 'שדה אליהו'),
  array('id' => '1165','city' => 'שדה אליעזר'),
  array('id' => '1166','city' => 'שדה בוקר'),
  array('id' => '1167','city' => 'שדה דוד'),
  array('id' => '1168','city' => 'שדה ורבורג'),
  array('id' => '1169','city' => 'שדה יואב'),
  array('id' => '1170','city' => 'שדה יעקב'),
  array('id' => '1171','city' => 'שדה יצחק'),
  array('id' => '1172','city' => 'שדה משה'),
  array('id' => '1173','city' => 'שדה נחום'),
  array('id' => '1174','city' => 'שדה נחמיה'),
  array('id' => '1175','city' => 'שדה ניצן'),
  array('id' => '1176','city' => 'שדה עוזיהו'),
  array('id' => '1177','city' => 'שדה צבי'),
  array('id' => '1178','city' => 'שדות ים'),
  array('id' => '1179','city' => 'שדות מיכה'),
  array('id' => '1180','city' => 'שדי אברהם'),
  array('id' => '1181','city' => 'שדי חמד'),
  array('id' => '1182','city' => 'שדי תרומות'),
  array('id' => '1183','city' => 'שדמה'),
  array('id' => '1184','city' => 'שדמות דבורה'),
  array('id' => '1185','city' => 'שדמות מחולה'),
  array('id' => '1186','city' => 'שדרות'),
  array('id' => '1187','city' => 'שואבה'),
  array('id' => '1188','city' => 'שובה'),
  array('id' => '1189','city' => 'שובל'),
  array('id' => '1190','city' => 'שוהם'),
  array('id' => '1191','city' => 'שומרה'),
  array('id' => '1192','city' => 'שומריה'),
  array('id' => '1193','city' => 'שוקדה'),
  array('id' => '1194','city' => 'שורש'),
  array('id' => '1195','city' => 'שורשים'),
  array('id' => '1196','city' => 'שושנת העמקים'),
  array('id' => '1197','city' => 'שזור'),
  array('id' => '1198','city' => 'שחר'),
  array('id' => '1199','city' => 'שחרות'),
  array('id' => '1200','city' => 'שיבולים'),
  array('id' => '1201','city' => 'שיטים'),
  array('id' => '1202','city' => 'שייח\' דנון'),
  array('id' => '1203','city' => 'שילה'),
  array('id' => '1204','city' => 'שילת'),
  array('id' => '1205','city' => 'שכניה'),
  array('id' => '1206','city' => 'שלווה'),
  array('id' => '1207','city' => 'שלווה במדבר'),
  array('id' => '1208','city' => 'שלוחות'),
  array('id' => '1209','city' => 'שלומי'),
  array('id' => '1210','city' => 'שלומית'),
  array('id' => '1211','city' => 'שמיר'),
  array('id' => '1212','city' => 'שמעה'),
  array('id' => '1213','city' => 'שמרת'),
  array('id' => '1214','city' => 'שמשית'),
  array('id' => '1215','city' => 'שני'),
  array('id' => '1216','city' => 'שניר'),
  array('id' => '1217','city' => 'שעב'),
  array('id' => '1218','city' => 'שעורים'),
  array('id' => '1219','city' => 'שעל'),
  array('id' => '1220','city' => 'שעלבים'),
  array('id' => '1221','city' => 'שער אפרים'),
  array('id' => '1222','city' => 'שער הגולן'),
  array('id' => '1223','city' => 'שער העמקים'),
  array('id' => '1224','city' => 'שער מנשה'),
  array('id' => '1225','city' => 'שערי תקווה'),
  array('id' => '1226','city' => 'שפיים'),
  array('id' => '1227','city' => 'שפיר'),
  array('id' => '1228','city' => 'שפר'),
  array('id' => '1229','city' => 'שפרעם'),
  array('id' => '1230','city' => 'שקד'),
  array('id' => '1231','city' => 'שקף'),
  array('id' => '1232','city' => 'שרונה'),
  array('id' => '1233','city' => 'שריגים )לי-און('),
  array('id' => '1234','city' => 'שריד'),
  array('id' => '1235','city' => 'שרשרת'),
  array('id' => '1236','city' => 'שתולה'),
  array('id' => '1237','city' => 'שתולים'),
  array('id' => '1238','city' => 'תאשור'),
  array('id' => '1239','city' => 'תדהר'),
  array('id' => '1240','city' => 'תובל'),
  array('id' => '1241','city' => 'תומר'),
  array('id' => '1242','city' => 'תושיה'),
  array('id' => '1243','city' => 'תימורים'),
  array('id' => '1244','city' => 'תירוש'),
  array('id' => '1245','city' => 'תל אביב - יפו'),
  array('id' => '1246','city' => 'תל יוסף'),
  array('id' => '1247','city' => 'תל יצחק'),
  array('id' => '1248','city' => 'תל מונד'),
  array('id' => '1249','city' => 'תל עדשים'),
  array('id' => '1250','city' => 'תל קציר'),
  array('id' => '1251','city' => 'תל שבע'),
  array('id' => '1252','city' => 'תל תאומים'),
  array('id' => '1253','city' => 'תלם'),
  array('id' => '1254','city' => 'תלמי אליהו'),
  array('id' => '1255','city' => 'תלמי אלעזר'),
  array('id' => '1256','city' => 'תלמי ביל"ו'),
  array('id' => '1257','city' => 'תלמי יוסף'),
  array('id' => '1258','city' => 'תלמי יחיאל'),
  array('id' => '1259','city' => 'תלמי יפה'),
  array('id' => '1260','city' => 'תלמים'),
  array('id' => '1261','city' => 'תמרת'),
  array('id' => '1262','city' => 'תנובות'),
  array('id' => '1263','city' => 'תעוז'),
  array('id' => '1264','city' => 'תפרח'),
  array('id' => '1265','city' => 'תקומה'),
  array('id' => '1266','city' => 'תקוע'),
  array('id' => '1267','city' => 'תראבין א-צאנע )שבט('),
  array('id' => '1268','city' => 'תראבין א-צאנע)ישוב('),
  array('id' => '1269','city' => 'תרום')
);
